In [1]:
library(ggplot2)
library(data.table)
library(stringr)
theme_set(theme_bw())

In [9]:
tools = c('singlem', 'sylph')
d1 = data.table(tool = tools, sample = "SRR8648366")

In [ ]:
readit = function(tool, sample){
    to_read = paste0('output_',tool,'/', tool, '/',sample,'.profile')
    return(fread(to_read))
}
d2 = d1[, readit(tool, sample)[, c("coverage", "taxonomy")], by=list(tool, sample)]
d2[, relabu := coverage / sum(coverage, na.rm = TRUE), by = list(tool, sample)]
d2[, taxonomy := gsub("; ", ";", gsub("Root; ", "", taxonomy))]

In [40]:
m = dcast(d2, sample + taxonomy ~ tool, value.var = c("relabu", "coverage"), fill = 0)
setnames(m, names(m), gsub("_", "__", names(m)))

In [ ]:
format_table <- function(m) {
    ra_cols <- grep("^relabu_|_relabu$", names(m), value = TRUE)
    mtmp = m[which(!grepl("^coverage_|_coverage$", names(m))), with = FALSE]
    mtmp[
        ,
        c(ra_cols, "taxonomy") := c(
            lapply(.SD[, ra_cols, with = FALSE], scales::label_percent()),
            list(purrr::map_chr(strsplit(taxonomy, "; ?"), function(x) tail(x,1)))
        )
    ][]
}

In [ ]:
# kingdom
format_table(
    m[grep("d__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";p__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy    relabu__singlem relabu__sylph
1 SRR8648366 d__Archaea  1%              1%
2 SRR8648366 d__Bacteria 99%             99%

In [62]:
# phylum
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";p__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";c__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy            relabu__singlem relabu__sylph
1 SRR8648366 p__Actinobacteriota 60.7%           59.192%
2 SRR8648366 p__Bacteroidota     9.1%            8.933%
3 SRR8648366 p__Firmicutes       2.1%            7.809%
4 SRR8648366 p__Firmicutes_A     3.1%            10.387%
5 SRR8648366 p__Proteobacteria   14.6%           10.446%

In [63]:
# class
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";c__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";o__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy               relabu__singlem relabu__sylph
1 SRR8648366 c__Actinomycetia       57.1%           58.88%
2 SRR8648366 c__Bacteroidia         8.6%            8.93%
3 SRR8648366 c__Bacilli             2.1%            7.81%
4 SRR8648366 c__Clostridia          3.1%            10.39%
5 SRR8648366 c__Gammaproteobacteria 13.3%           9.52%

In [64]:
# order
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";o__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";f__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy                 relabu__singlem relabu__sylph
1  SRR8648366 o__Actinomycetales       35.51964%       40.2727%
2  SRR8648366 o__Mycobacteriales       13.11559%       17.2577%
3  SRR8648366 o__Propionibacteriales   6.08802%        1.0262%
4  SRR8648366 o__Bacteroidales         1.49753%        7.0323%
5  SRR8648366 o__Flavobacteriales      4.13192%        1.9010%
6  SRR8648366 o__Lactobacillales       0.64331%        4.1470%
7  SRR8648366 o__Staphylococcales      0.14799%        1.2683%
8  SRR8648366 o__Christensenellales    0.29246%        1.3574%
9  SRR8648366 o__Clostridiales         0.58894%        2.2603%
10 SRR8648366 o__Oscillospirales       0.60279%        2.0701%
11 SRR8648366 o__Peptostreptococcales  0.64859%        1.6328%
12 SRR8648366 o__Saccharofermentanales 0.31083%        1.7314%
13 SRR8648366 o__Burkholderiales       0.64809%        1.3604%
14 SRR8648366 o__Pseudomonadales       2.15669%        3.9873%
15 SRR8648366 o__Xanthomonadales       8.69599%        3.1558%

In [65]:
# family
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";f__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";g__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy                relabu__singlem relabu__sylph
1  SRR8648366 f__Brevibacteriaceae    1.17638%        4.8488%
2  SRR8648366 f__Dermatophilaceae     24.65160%       32.9681%
3  SRR8648366 f__Mycobacteriaceae     7.82466%        16.3459%
4  SRR8648366 f__Propionibacteriaceae 2.32079%        1.0262%
5  SRR8648366 f__Bacteroidaceae       0.26654%        1.6332%
6  SRR8648366 f__Dysgonomonadaceae    0.49255%        2.6284%
7  SRR8648366 f__Flavobacteriaceae    2.52692%        1.6350%
8  SRR8648366 f__Lactobacillaceae     0.21871%        1.3857%
9  SRR8648366 f__Streptococcaceae     0.31058%        2.4742%
10 SRR8648366 f__Clostridiaceae       0.58894%        2.2603%
11 SRR8648366 f__Oscillospiraceae     0.34431%        1.1302%
12 SRR8648366 f__Acidaminobacteraceae 0.22601%        1.3463%
13 SRR8648366 f__DTU023               0.27081%        1.6500%
14 SRR8648366 f__Burkholderiaceae     0.51872%        1.2722%
15 SRR8648366 f__Oleiphilaceae        0.49305%        1.4986%
16 SRR8648366 f__Pseudomonadaceae     0.31763%        1.5901%
17 SRR8648366 f__Xanthomonadaceae     2.21685%        3.1558%

In [66]:
# How well does genus level rescue some of the missing genomes? First need to remake the table with genus level, annoying since kraken profiles are filled, when the rest aren't.
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";g__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";s__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy              relabu__singlem relabu__sylph
1  SRR8648366 g__Brevibacterium     0.934%          4.8488%
2  SRR8648366 g__F2B08              2.608%          13.4284%
3  SRR8648366 g__Ornithinimicrobium 4.644%          18.7970%
4  SRR8648366 g__Corynebacterium    1.867%          12.7787%
5  SRR8648366 g__Dietzia            0.579%          1.0383%
6  SRR8648366 g__Mycobacterium      2.122%          2.1299%
7  SRR8648366 g__Prevotella         0.194%          1.1673%
8  SRR8648366 g__Proteiniphilum     0.289%          1.4499%
9  SRR8648366 g__Aequorivita        0.649%          1.5821%
10 SRR8648366 g__Streptococcus      0.311%          2.4742%
11 SRR8648366 g__Clostridium        0.564%          2.2498%
12 SRR8648366 g__DUPT01             0.169%          1.1256%
13 SRR8648366 g__Oligella           0.131%          1.1316%
14 SRR8648366 g__Marinobacter       0.474%          1.4986%
15 SRR8648366 g__Luteimonas         0.528%          2.7921%

In [67]:
# Species level
format_table(m[!grepl("d__Archaea", taxonomy) & grepl(";s__", taxonomy)][relabu__sylph > 0.01])

   sample     taxonomy                          relabu__singlem relabu__sylph
1  SRR8648366 s__Brevibacterium intestinavium   0.6838%         4.2619%
2  SRR8648366 s__F2B08 sp012729695              0.1792%         1.1249%
3  SRR8648366 s__F2B08 sp012838445              2.0117%         12.3035%
4  SRR8648366 s__Ornithinimicrobium sp003577095 1.4253%         18.7970%
5  SRR8648366 s__Corynebacterium casei          0.1618%         1.2115%
6  SRR8648366 s__Corynebacterium humireducens   0.6176%         3.2129%
7  SRR8648366 s__Corynebacterium pollutisoli    0.2212%         1.5285%
8  SRR8648366 s__Corynebacterium sp012838715    0.0803%         1.0560%
9  SRR8648366 s__Corynebacterium sp012838985    0.3758%         5.1265%
10 SRR8648366 s__Dietzia sp012841845            0.1445%         1.0383%
11 SRR8648366 s__Mycobacterium koreense         0.4910%         1.7776%
12 SRR8648366 s__Proteiniphilum sp016916535     0.1968%         1.0491%
13 SRR8648366 s__Aequorivita sinensis           0.2263%         1.4273%
14 SRR8648366 s__Streptococcus alactolyticus    0.3106%         2.4134%
15 SRR8648366 s__Clostridium sp000435835        0.0790%         1.9526%
16 SRR8648366 s__Oligella sp012511095           0.1228%         1.1316%
17 SRR8648366 s__Marinobacter vinifirmus        0.2154%         1.3616%
18 SRR8648366 s__Luteimonas sp001717465         0.2519%         1.5182%
19 SRR8648366 s__Luteimonas sp012515985         0.0478%         1.2739%

In [82]:
m[, grep("s__Corynebacterium", taxonomy, value = TRUE)][1]
m[, grep("s__F2B08", taxonomy, value = TRUE)][1]
m[, grep("s__Ornithinimicrobium", taxonomy, value = TRUE)][1]

[1] "d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Mycobacteriales;f__Mycobacteriaceae;g__Corynebacterium;s__Corynebacterium casei"

[1] "d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Actinomycetales;f__Dermatophilaceae;g__F2B08;s__F2B08 sp012729695"

[1] "d__Bacteria;p__Actinobacteriota;c__Actinomycetia;o__Actinomycetales;f__Dermatophilaceae;g__Ornithinimicrobium;s__Ornithinimicrobium sp001942405"