In [3]:
library(ggplot2)
library(data.table)
library(stringr)
theme_set(theme_bw())

In [4]:
tools = c('singlem', 'sylph')
d1 = data.table(tool = tools, sample = "SRR8648366")

In [5]:
readit = function(tool, sample){
    to_read = paste0('output_',tool,'/', tool, '/',sample,'.profile')
    return(fread(to_read))
}
d2 = d1[, readit(tool, sample)[, c("coverage", "taxonomy")], by=list(tool, sample)]
d2[, relabu := coverage / sum(coverage, na.rm = TRUE), by = list(tool, sample)]
d2[, taxonomy := gsub("; ", ";", gsub("Root; ", "", taxonomy))]

In [6]:
m = dcast(d2, sample + taxonomy ~ tool, value.var = c("relabu", "coverage"), fill = 0)
setnames(m, names(m), gsub("_", "__", names(m)))

In [13]:
format_table <- function(m) {
    ra_cols <- grep("^relabu_|_relabu$", names(m), value = TRUE)
    mtmp = m[,which(!grepl("^coverage_|_coverage$", names(m))), with = FALSE]
    mtmp[
        ,
        c(ra_cols, "taxonomy") := c(
            lapply(.SD[, ra_cols, with = FALSE], scales::label_percent()),
            list(purrr::map(strsplit(taxonomy, "; ?"), function(x) paste0(tail(x,2), collapse = "; ")))
        )
    ][]
}

In [14]:
# kingdom
format_table(
    m[grep("d__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";p__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy    relabu__singlem relabu__sylph
1 SRR8648366 d__Archaea  1%              1%
2 SRR8648366 d__Bacteria 99%             99%

In [15]:
# phylum
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";p__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";c__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy                         relabu__singlem relabu__sylph
1 SRR8648366 d__Bacteria; p__Actinobacteriota 60.7%           59.160%
2 SRR8648366 d__Bacteria; p__Bacteroidota     9.1%            8.938%
3 SRR8648366 d__Bacteria; p__Firmicutes       2.1%            7.805%
4 SRR8648366 d__Bacteria; p__Firmicutes_A     3.1%            10.407%
5 SRR8648366 d__Bacteria; p__Proteobacteria   14.6%           10.440%

In [16]:
# class
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";c__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";o__.*", "", taxonomy))][relabu__sylph > 0.01]
)

  sample     taxonomy                                  relabu__singlem
1 SRR8648366 p__Actinobacteriota; c__Actinomycetia     57.1%
2 SRR8648366 p__Bacteroidota; c__Bacteroidia           8.6%
3 SRR8648366 p__Firmicutes; c__Bacilli                 2.1%
4 SRR8648366 p__Firmicutes_A; c__Clostridia            3.1%
5 SRR8648366 p__Proteobacteria; c__Gammaproteobacteria 13.3%
  relabu__sylph
1 58.84%
2 8.94%
3 7.80%
4 10.41%
5 9.52%

In [17]:
# order
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";o__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";f__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy                                   relabu__singlem
1  SRR8648366 c__Actinomycetia; o__Actinomycetales       35.51955%
2  SRR8648366 c__Actinomycetia; o__Mycobacteriales       13.11556%
3  SRR8648366 c__Actinomycetia; o__Propionibacteriales   6.08801%
4  SRR8648366 c__Bacteroidia; o__Bacteroidales           1.49753%
5  SRR8648366 c__Bacteroidia; o__Flavobacteriales        4.13191%
6  SRR8648366 c__Bacilli; o__Lactobacillales             0.64331%
7  SRR8648366 c__Bacilli; o__Staphylococcales            0.14799%
8  SRR8648366 c__Clostridia; o__Christensenellales       0.29246%
9  SRR8648366 c__Clostridia; o__Clostridiales            0.58894%
10 SRR8648366 c__Clostridia; o__Oscillospirales          0.60279%
11 SRR8648366 c__Clostridia; o__Peptostreptococcales     0.64859%
12 SRR8648366 c__Clostridia; o__Saccharofermentanales    0.31083%
13 SRR8648366 c__Gammaproteobacteria; o__Burkholderiales 0.64809%
14 SRR8648366 c__Gammaproteobacteria; o__Pseudomonadales 2.15669%
15 SRR8648366 c__Gammaproteobacteria; o__Xanthomonadales 8.69597%
   relabu__sylph
1  40.2508%
2  17.2483%
3  1.0256%
4  7.0385%
5  1.9000%
6  4.1448%
7  1.2676%
8  1.3567%
9  2.2670%
10 2.0690%
11 1.6319%
12 1.7305%
13 1.3597%
14 3.9852%
15 3.1541%

In [18]:
# family
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";f__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";g__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy                                         relabu__singlem
1  SRR8648366 o__Actinomycetales; f__Brevibacteriaceae         1.17638%
2  SRR8648366 o__Actinomycetales; f__Dermatophilaceae          24.65154%
3  SRR8648366 o__Mycobacteriales; f__Mycobacteriaceae          7.82464%
4  SRR8648366 o__Propionibacteriales; f__Propionibacteriaceae  2.32079%
5  SRR8648366 o__Bacteroidales; f__Bacteroidaceae              0.26653%
6  SRR8648366 o__Bacteroidales; f__Dysgonomonadaceae           0.49255%
7  SRR8648366 o__Flavobacteriales; f__Flavobacteriaceae        2.52692%
8  SRR8648366 o__Lactobacillales; f__Lactobacillaceae          0.21871%
9  SRR8648366 o__Lactobacillales; f__Streptococcaceae          0.31058%
10 SRR8648366 o__Clostridiales; f__Clostridiaceae              0.58894%
11 SRR8648366 o__Oscillospirales; f__Oscillospiraceae          0.34431%
12 SRR8648366 o__Peptostreptococcales; f__Acidaminobacteraceae 0.22601%
13 SRR8648366 o__Saccharofermentanales; f__DTU023              0.27081%
14 SRR8648366 o__Burkholderiales; f__Burkholderiaceae          0.51872%
15 SRR8648366 o__Pseudomonadales; f__Oleiphilaceae             0.49305%
16 SRR8648366 o__Pseudomonadales; f__Pseudomonadaceae          0.31763%
17 SRR8648366 o__Xanthomonadales; f__Xanthomonadaceae          2.21684%
   relabu__sylph
1  4.8462%
2  32.9502%
3  16.3370%
4  1.0256%
5  1.6323%
6  2.6270%
7  1.6341%
8  1.3850%
9  2.4729%
10 2.2670%
11 1.1296%
12 1.3456%
13 1.6491%
14 1.2715%
15 1.4978%
16 1.5892%
17 3.1541%

In [19]:
# How well does genus level rescue some of the missing genomes? First need to remake the table with genus level, annoying since kraken profiles are filled, when the rest aren't.
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";g__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";s__.*", "", taxonomy))][relabu__sylph > 0.01]
)

   sample     taxonomy                                   relabu__singlem
1  SRR8648366 f__Brevibacteriaceae; g__Brevibacterium    0.933%
2  SRR8648366 f__Dermatophilaceae; g__F2B08              2.608%
3  SRR8648366 f__Dermatophilaceae; g__Ornithinimicrobium 4.644%
4  SRR8648366 f__Mycobacteriaceae; g__Corynebacterium    1.867%
5  SRR8648366 f__Mycobacteriaceae; g__Dietzia            0.579%
6  SRR8648366 f__Mycobacteriaceae; g__Mycobacterium      2.122%
7  SRR8648366 f__Bacteroidaceae; g__Prevotella           0.194%
8  SRR8648366 f__Dysgonomonadaceae; g__Proteiniphilum    0.289%
9  SRR8648366 f__Flavobacteriaceae; g__Aequorivita       0.649%
10 SRR8648366 f__Streptococcaceae; g__Streptococcus      0.311%
11 SRR8648366 f__Clostridiaceae; g__Clostridium          0.564%
12 SRR8648366 f__Acidaminobacteraceae; g__DUPT01         0.169%
13 SRR8648366 f__Burkholderiaceae; g__Oligella           0.131%
14 SRR8648366 f__Oleiphilaceae; g__Marinobacter          0.474%
15 SRR8648366 f__Xanthomonadaceae; g__Luteimonas         0.528%
   relabu__sylph
1  4.8462%
2  13.4211%
3  18.7868%
4  12.7717%
5  1.0377%
6  2.1288%
7  1.1667%
8  1.4491%
9  1.5812%
10 2.4729%
11 2.2486%
12 1.1250%
13 1.1310%
14 1.4978%
15 2.7906%

In [20]:
# Species level
format_table(m[!grepl("d__Archaea", taxonomy) & grepl(";s__", taxonomy)][relabu__sylph > 0.01])

   sample     taxonomy
1  SRR8648366 g__Brevibacterium; s__Brevibacterium intestinavium
2  SRR8648366 g__F2B08; s__F2B08 sp012729695
3  SRR8648366 g__F2B08; s__F2B08 sp012838445
4  SRR8648366 g__Ornithinimicrobium; s__Ornithinimicrobium sp003577095
5  SRR8648366 g__Corynebacterium; s__Corynebacterium casei
6  SRR8648366 g__Corynebacterium; s__Corynebacterium humireducens
7  SRR8648366 g__Corynebacterium; s__Corynebacterium pollutisoli
8  SRR8648366 g__Corynebacterium; s__Corynebacterium sp012838715
9  SRR8648366 g__Corynebacterium; s__Corynebacterium sp012838985
10 SRR8648366 g__Dietzia; s__Dietzia sp012841845
11 SRR8648366 g__Mycobacterium; s__Mycobacterium koreense
12 SRR8648366 g__Proteiniphilum; s__Proteiniphilum sp016916535
13 SRR8648366 g__Aequorivita; s__Aequorivita sinensis
14 SRR8648366 g__Streptococcus; s__Streptococcus alactolyticus
15 SRR8648366 g__Clostridium; s__Clostridium sp000435835
16 SRR8648366 g__Oligella; s__Oligella sp012511095
17 SRR8648366 g__Marinobacter; s__Marinobacter vinifirmus
18 SRR8648366 g__Luteimonas; s__Luteimonas sp001717465
19 SRR8648366 g__Luteimonas; s__Luteimonas sp012515985
   relabu__singlem relabu__sylph
1  0.6838%         4.2596%
2  0.1792%         1.1243%
3  2.0117%         12.2968%
4  1.4253%         18.7868%
5  0.1618%         1.2108%
6  0.6176%         3.2112%
7  0.2212%         1.5277%
8  0.0803%         1.0554%
9  0.3758%         5.1237%
10 0.1445%         1.0377%
11 0.4910%         1.7766%
12 0.1968%         1.0485%
13 0.2263%         1.4265%
14 0.3106%         2.4121%
15 0.0790%         1.9515%
16 0.1228%         1.1310%
17 0.2154%         1.3609%
18 0.2519%         1.5174%
19 0.0478%         1.2732%